Bug Fix & Functional Update
YDX-2147483647/BIT-enhanced pull request #33
Opened 2024-10-08 03:47 UTC by CJJ-amateur-programmer

BIT-Programming-Detect：
1.从某字符开始探测，结果仍然从第0个字符开始，已修改；
2.半秒检查一次测试结果太频繁，容易被封IP，测试发现改成一秒一次即可

BIT-乐学-修改侧边栏课程-GUI：
1.更换课程列表数据来源，能够在更新课程列表信息时按照课程结束时间倒序展示；
2.更新课程列表时，能够对比并整合课程列表，将新增的课程插入“隐藏的课程”列表头部并用红色粗体标识；
3.添加了图标更换的功能，双击弹窗列表中项目的图标并输入新图标名称，可以更改图标；
4.解决更改课程名称时写入html标签被解析的问题；
5.解决代码在获取课程名称时前后保留大量空格和换行符的毛病
可参见 https://github.com/CJJ-amateur-programmer/BIT_lexue_sidebar_optimizer

2024-10-08 05:55 UTC, YDX-2147483647 requested changes
呃，能否把有一千多字的那些行拆开？这样我很难看清改了什么……上次我都给拆开了，但你好像又给合起来了？

2024-10-08 05:55 UTC, YDX-2147483647 commented on TamperMonkey/BIT-乐学-修改侧边栏课程-GUI.user.js
>  // ==/UserScript==
```suggestion
// @grant        GM_setValue
// @grant        GM_registerMenuCommand
// ==/UserScript==
```

GreasyFork 会自己加链接，自己标了也会被改，所以不用标。

https://greasyfork.org/zh-CN/help/meta-keys#meta-updateURL

2024-10-08 05:55 UTC, YDX-2147483647 commented on TamperMonkey/BIT-乐学-修改侧边栏课程-GUI.user.js
> +    xhr.open('POST', `https://lexue.bit.edu.cn/lib/ajax/service.php?sesskey=${M.cfg.sesskey}&info=core_course_get_enrolled_courses_by_timeline_classification`, true)
https://results.pre-commit.ci/run/github/330974151/1728363997.VtGk4APBTq2u1uiP1SuJAw 说这个`M`没有定义，是否有误？

2024-10-08 05:57 UTC, YDX-2147483647 commented on TamperMonkey/BIT-乐学-修改侧边栏课程-GUI.user.js
> +        shown_courses.push([shown_lis[i].dataset.id, shown_lis[i].innerText.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll(' ', '&nbsp;'), shown_lis[i].querySelec
无论`innerText`还是`textContent`，按理说都不会出现`&amp;`；似乎只有`innerHTML`才会？我怀疑是写的时候错了，不是读的问题。

2024-10-08 05:57 UTC, CJJ-amateur-programmer commented on TamperMonkey/BIT-乐学-修改侧边栏课程-GUI.user.js
> +    xhr.open('POST', `https://lexue.bit.edu.cn/lib/ajax/service.php?sesskey=${M.cfg.sesskey}&info=core_course_get_enrolled_courses_by_timeline_classification`, true)
M是乐学的全局变量，经测试能够正常使用

2024-10-08 06:01 UTC, YDX-2147483647 commented on TamperMonkey/BIT-乐学-修改侧边栏课程-GUI.user.js
> +    xhr.open('POST', `https://lexue.bit.edu.cn/lib/ajax/service.php?sesskey=${M.cfg.sesskey}&info=core_course_get_enrolled_courses_by_timeline_classification`, true)
原来如此；那建议在开头标一下。

```suggestion
  // 乐学提供
  /* global M */
```

https://eslint.org/docs/latest/use/configure/language-options#using-configuration-comments

2024-10-08 06:01 UTC, CJJ-amateur-programmer commented
> 感谢更新，不过能否把有一千多字的那些行拆开？这样我很难看清改了什么……上次我都给拆开了，但你好像又给合起来了？

如果不放在一行内，读取shown_lis和hidden_lis的innerText时会出现很多空格和换行，所以我为了追求简洁把空白符全删了，放在一行内

2024-10-08 06:05 UTC, CJJ-amateur-programmer commented on TamperMonkey/BIT-乐学-修改侧边栏课程-GUI.user.js
> +        shown_courses.push([shown_lis[i].dataset.id, shown_lis[i].innerText.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll(' ', '&nbsp;'), shown_lis[i].querySelec
如果不替换&<>三个字符，修改课程名称后，运行rewrite_sidebar重写侧边栏时，诸如`<b style="color:red">name</b>`的课程名称将会被解析为HTML标签

2024-10-08 06:35 UTC, YDX-2147483647 commented on TamperMonkey/BIT-乐学-修改侧边栏课程-GUI.user.js
> +        shown_courses.push([shown_lis[i].dataset.id, shown_lis[i].innerText.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll(' ', '&nbsp;'), shown_lis[i].querySelec
我还是倾向于写有问题。如果课程名称改成`&amp;`，那下回是不是就变成`&`了？也许写的时候先用`innerHTML`建好元素，不填课程名称，让选中子元素用`innerText`或`textContent`补课程名称比较好。

2024-10-08 06:51 UTC, CJJ-amateur-programmer commented on TamperMonkey/BIT-乐学-修改侧边栏课程-GUI.user.js
> +        shown_courses.push([shown_lis[i].dataset.id, shown_lis[i].innerText.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll(' ', '&nbsp;'), shown_lis[i].querySelec
经过测试，如下的课程名称能够正常显示，不被解析：
`<b>Test & &amp; &lt; &gt;</b>`
你可以把某个课程改成这个名称试试看

2024-10-08 07:11 UTC, CJJ-amateur-programmer commented on TamperMonkey/BIT-乐学-修改侧边栏课程-GUI.user.js
> +        shown_courses.push([shown_lis[i].dataset.id, shown_lis[i].innerText.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll(' ', '&nbsp;'), shown_lis[i].querySelec
如果在devtools中选中一个元素，运行`$0.innerText="<b>innerText test</b>"`，发现HTML标签确实没有被解析；检查`$0.innerHTML`，返回`'&lt;b&gt;innerText test&lt;/b&gt;'`，证明没有被解析就是因为已经经过转义

2024-10-08 07:26 UTC, YDX-2147483647 commented on TamperMonkey/BIT-乐学-修改侧边栏课程-GUI.user.js
> +        shown_courses.push([shown_lis[i].dataset.id, shown_lis[i].innerText.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll(' ', '&nbsp;'), shown_lis[i].querySelec
> 经过测试，如下的课程名称能够正常显示，不被解析：
> `<b>Test & &amp; &lt; &gt;</b>`
> 你可以把某个课程改成这个名称试试看

我刚才试了一下，只用GUI操作确实没问题，但直接编辑存储，写入`"<b>Test & &amp; &lt; &gt;</b>"`会显示为加粗的`Test & & < >`。

2024-10-09 07:33 UTC, YDX-2147483647 commented
编解码及换行的问题我还是保留意见，不过其它我都检查过了，功能也试了没问题。只差更新文档就能发布了，比如下面这些。

https://github.com/YDX-2147483647/BIT-enhanced/blob/a782a76ff6f4888096e643ce4445337d3a33c8e0/TamperMonkey/BIT-%E4%B9%90%E5%AD%A6-%E4%BF%AE%E6%94%B9%E4%BE%A7%E8%BE%B9%E6%A0%8F%E8%AF%BE%E7%A8%8B-GUI.md?plain=1#L25
https://github.com/YDX-2147483647/BIT-enhanced/blob/a782a76ff6f4888096e643ce4445337d3a33c8e0/TamperMonkey/BIT-%E4%B9%90%E5%AD%A6-%E4%BF%AE%E6%94%B9%E4%BE%A7%E8%BE%B9%E6%A0%8F%E8%AF%BE%E7%A8%8B.md?plain=1#L47

这几天我们谁有空谁更新一下吧。 🚀

2024-10-10 06:46 UTC, merged

2024-10-10 06:48 UTC, YDX-2147483647 commented
已经发布了！:tada:

[BIT-Programming-Detect](https://greasyfork.org/zh-CN/scripts/488587-bit-programming-detect)
[BIT-乐学-修改侧边栏课程-GUI](https://greasyfork.org/zh-CN/scripts/488788-bit-%E4%B9%90%E5%AD%A6-%E4%BF%AE%E6%94%B9%E4%BE%A7%E8%BE%B9%E6%A0%8F%E8%AF%BE%E7%A8%8B-gui)

2024-10-10 15:38 UTC, CJJ-amateur-programmer commented
文档有个小问题，课程更新后需要点击菜单栏的“更新课程并修改侧边栏”才检查更新，文档中的描述看起来像自动更新……

2024-10-11 06:02 UTC, YDX-2147483647 commented
呃，要不你自己改一下另发 PR？

https://github.com/YDX-2147483647/BIT-enhanced/edit/main/TamperMonkey/BIT-%E4%B9%90%E5%AD%A6-%E4%BF%AE%E6%94%B9%E4%BE%A7%E8%BE%B9%E6%A0%8F%E8%AF%BE%E7%A8%8B-GUI.md